"""initial

Revision ID: d2e331360665
Revises: 
Create Date: 2026-07-08 14:24:35.000447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e331360665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('season_type', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_rosters', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scoring_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roster_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_league_id', sa.String(), nullable=True),
    sa.Column('draft_id', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('league_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('nfl_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('season_type', sa.String(), nullable=True),
    sa.Column('season_start_date', sa.String(), nullable=True),
    sa.Column('previous_season', sa.String(), nullable=True),
    sa.Column('leg', sa.Integer(), nullable=True),
    sa.Column('league_season', sa.String(), nullable=True),
    sa.Column('league_create_season', sa.String(), nullable=True),
    sa.Column('display_week', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('gsis_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('fantasy_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('injury_start_date', sa.String(), nullable=True),
    sa.Column('sportradar_id', sa.String(), nullable=True),
    sa.Column('rotowire_id', sa.Integer(), nullable=True),
    sa.Column('rotoworld_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('yahoo_id', sa.String(), nullable=True),
    sa.Column('fantasy_data_id', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.String(), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('depth_chart_position', sa.String(), nullable=True),
    sa.Column('depth_chart_order', sa.Integer(), nullable=True),
    sa.Column('search_rank', sa.Integer(), nullable=True),
    sa.Column('search_full_name', sa.String(), nullable=True),
    sa.Column('search_first_name', sa.String(), nullable=True),
    sa.Column('search_last_name', sa.String(), nullable=True),
    sa.Column('practice_participation', sa.String(), nullable=True),
    sa.Column('news_updated', sa.BigInteger(), nullable=True),
    sa.Column('birth_country', sa.String(), nullable=True),
    sa.Column('birth_city', sa.String(), nullable=True),
    sa.Column('birth_state', sa.String(), nullable=True),
    sa.Column('rookie_year', sa.Integer(), nullable=True),
    sa.Column('injury_notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('drafts',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('season_type', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slot_to_roster_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_table('league_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_user')
    )
    op.create_table('matchups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('custom_points', sa.Float(), nullable=True),
    sa.Column('starters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('starters_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('players_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'week', 'roster_id', name='uq_matchup')
    )
    op.create_table('player_weekly_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('passing_yards', sa.Integer(), nullable=True),
    sa.Column('passing_tds', sa.Integer(), nullable=True),
    sa.Column('passing_interceptions', sa.Integer(), nullable=True),
    sa.Column('passing_2pt_conversions', sa.Integer(), nullable=True),
    sa.Column('sacks_suffered', sa.Integer(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_tds', sa.Integer(), nullable=True),
    sa.Column('rushing_2pt_conversions', sa.Integer(), nullable=True),
    sa.Column('rushing_fumbles', sa.Integer(), nullable=True),
    sa.Column('rushing_fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('receiving_2pt_conversions', sa.Integer(), nullable=True),
    sa.Column('receiving_fumbles', sa.Integer(), nullable=True),
    sa.Column('receiving_fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('fumbles_own_recovery', sa.Integer(), nullable=True),
    sa.Column('special_teams_tds', sa.Integer(), nullable=True),
    sa.Column('kickoff_return_yards', sa.Integer(), nullable=True),
    sa.Column('kickoff_returns', sa.Integer(), nullable=True),
    sa.Column('punt_return_yards', sa.Integer(), nullable=True),
    sa.Column('punt_returns', sa.Integer(), nullable=True),
    sa.Column('fg_made', sa.Integer(), nullable=True),
    sa.Column('fg_att', sa.Integer(), nullable=True),
    sa.Column('fg_made_0_19', sa.Integer(), nullable=True),
    sa.Column('fg_made_20_29', sa.Integer(), nullable=True),
    sa.Column('fg_made_30_39', sa.Integer(), nullable=True),
    sa.Column('fg_made_40_49', sa.Integer(), nullable=True),
    sa.Column('fg_made_50_59', sa.Integer(), nullable=True),
    sa.Column('fg_made_60_', sa.Integer(), nullable=True),
    sa.Column('pat_made', sa.Integer(), nullable=True),
    sa.Column('pat_att', sa.Integer(), nullable=True),
    sa.Column('def_tackles_solo', sa.Integer(), nullable=True),
    sa.Column('def_tackles_with_assist', sa.Integer(), nullable=True),
    sa.Column('def_tackles_for_loss', sa.Integer(), nullable=True),
    sa.Column('def_sacks', sa.Float(), nullable=True),
    sa.Column('def_sack_yards', sa.Float(), nullable=True),
    sa.Column('def_interceptions', sa.Integer(), nullable=True),
    sa.Column('def_interception_yards', sa.Integer(), nullable=True),
    sa.Column('def_pass_defended', sa.Integer(), nullable=True),
    sa.Column('def_fumbles_forced', sa.Integer(), nullable=True),
    sa.Column('def_fumbles', sa.Integer(), nullable=True),
    sa.Column('def_qb_hits', sa.Integer(), nullable=True),
    sa.Column('def_tds', sa.Integer(), nullable=True),
    sa.Column('def_safeties', sa.Integer(), nullable=True),
    sa.Column('fg_missed', sa.Integer(), nullable=True),
    sa.Column('pat_missed', sa.Integer(), nullable=True),
    sa.Column('fg_blocked', sa.Integer(), nullable=True),
    sa.Column('pat_blocked', sa.Integer(), nullable=True),
    sa.Column('punt_blocked', sa.Integer(), nullable=True),
    sa.Column('kicks_blocked', sa.Integer(), nullable=True),
    sa.Column('fumble_recovery_opp', sa.Integer(), nullable=True),
    sa.Column('fumble_recovery_tds', sa.Integer(), nullable=True),
    sa.Column('fg_yds_bonus', sa.Integer(), nullable=True),
    sa.Column('def_4_and_stop', sa.Integer(), nullable=True),
    sa.Column('def_3_and_out', sa.Integer(), nullable=True),
    sa.Column('offense_snaps', sa.Integer(), nullable=True),
    sa.Column('defense_snaps', sa.Integer(), nullable=True),
    sa.Column('st_snaps', sa.Integer(), nullable=True),
    sa.Column('offense_pct', sa.Float(), nullable=True),
    sa.Column('defense_pct', sa.Float(), nullable=True),
    sa.Column('st_pct', sa.Float(), nullable=True),
    sa.Column('def_time_of_possession', sa.Integer(), nullable=True),
    sa.Column('def_plays', sa.Integer(), nullable=True),
    sa.Column('total_plays', sa.Integer(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('air_yards', sa.Integer(), nullable=True),
    sa.Column('racr', sa.Float(), nullable=True),
    sa.Column('wopr', sa.Float(), nullable=True),
    sa.Column('passing_air_yards', sa.Integer(), nullable=True),
    sa.Column('passing_epa', sa.Float(), nullable=True),
    sa.Column('receiving_epa', sa.Float(), nullable=True),
    sa.Column('rushing_epa', sa.Float(), nullable=True),
    sa.Column('pts_allowed', sa.Float(), nullable=True),
    sa.Column('yds_allowed', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week', 'season_type', name='uq_player_weekly')
    )
    op.create_index(op.f('ix_player_weekly_stats_player_id'), 'player_weekly_stats', ['player_id'], unique=False)
    op.create_table('playoff_brackets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('bracket_type', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_1', sa.Integer(), nullable=True),
    sa.Column('team_2', sa.Integer(), nullable=True),
    sa.Column('team_1_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team_2_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('loser', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'bracket_type', 'match_id', name='uq_bracket_match')
    )
    op.create_table('rosters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('starters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reserve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'roster_id', name='uq_roster_league')
    )
    op.create_index(op.f('ix_rosters_owner_id'), 'rosters', ['owner_id'], unique=False)
    op.create_table('traded_picks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('previous_owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'round', 'roster_id', name='uq_traded_pick')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_updated', sa.BigInteger(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roster_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leg', sa.Integer(), nullable=True),
    sa.Column('drops', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_picks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('created', sa.BigInteger(), nullable=True),
    sa.Column('consenter_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waiver_budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('draft_slot', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('picked_by', sa.String(), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'pick_no', name='uq_draft_pick')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_picks')
    op.drop_table('transactions')
    op.drop_table('traded_picks')
    op.drop_index(op.f('ix_rosters_owner_id'), table_name='rosters')
    op.drop_table('rosters')
    op.drop_table('playoff_brackets')
    op.drop_index(op.f('ix_player_weekly_stats_player_id'), table_name='player_weekly_stats')
    op.drop_table('player_weekly_stats')
    op.drop_table('matchups')
    op.drop_table('league_users')
    op.drop_table('drafts')
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('nfl_state')
    op.drop_table('leagues')
    # ### end Alembic commands ###
